version: 2.1

orbs:
  slack: circleci/slack@4.12.5

executors:
  pnpm-executor:
    docker:
      - image: cimg/node:20.5.0-browsers
    working_directory: /tmp/workspace

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: pnpm install --shamefully-hoist
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: pnpm run build
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - pnpm-lock.yaml
            - node_modules
            - cypress
            - cypress.config.ts
            - nuxt.config.ts
            - vitest.config.ts
            - tsconfig.json
            - assets
            - components
            - content
            - composables
            - layouts
            - pages
            - plugins
            - server
            - stores
            - tests
            - types
            - .nuxt
            - .output
            - .gitignore
            - sonar-project.properties
      - slack/notify:
          channel: circleci
          event: fail


workflows:
  flow:
    jobs:
      - build:
          context:
            - Slack
